export const PostActionTypes = {
    IS_LOADING: 'IS_LOADING',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POST: 'GET_POST',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    SAVE_POST_SUCCESS: 'SAVE_POST_SUCCESS',
    SAVE_POST_ERROR: 'SAVE_POST_ERROR'

};