export const PostActionTypes = {
    IS_LOADING: 'IS_LOADING',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POST: 'GET_POST',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS'

};